# .github/workflows/chromatic.yml

# Workflow name
name: "Release"

# Event for the workflow
on:
  push:
    branches:
      - "master" # 👈 Excludes the example branch
# List of jobs
jobs:
  release:
    # Operating System
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      issues: write
      pull-requests: write
    # Job steps
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: yarn
        # 👇 Adds Chromatic as a step in the workflow
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.CODE_ARTIFACT_PUBLISH_ROLE_ARN }}
          aws-region: us-east-1
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_REGION: us-east-1
        run: npx semantic-release
